name: End to End Testing

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@v0.3.1900000349
        with:
          push: never
          runCmd: echo hi