# This workflow pre-builds the dev container docker image used in Github Codespaces or if you run the devcontainer locally
# This will pre-install all the container features.
# The image is PRIVATE to the orginization; regardless, no sensitive data is exposed to the package stored in ghcr.io.
name: Prebuild Dev Container

on:
  push:
    branches: [fix/multi-platform-build]

env:
  DOCKER_IMAGE_NAME:

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        # Use a matrix strategy to run two jobs, one for amd64 and one for arm64.
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
      # Docker images require lowercase names, but GitHub repository may contain uppercase characters
      - name: downcase REPO
        run: |
          echo "DOCKER_IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build docker image used for local development (Dev Container) and CI testing
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ${{ env.DOCKER_IMAGE_NAME }}
          imageTag: ${{ matrix.os }}
          push: always

  # Combine the two images into one manifest and push with the :latest tag.
  combine:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push manifest
        run: |
          docker manifest create ${{ env.DOCKER_IMAGE_NAME }}:latest \
            --amend ${{ env.DOCKER_IMAGE_NAME }}:ubuntu-24.04-arm \
            --amend ${{ env.DOCKER_IMAGE_NAME }}:ubuntu-latest

          docker manifest push ${{ env.DOCKER_IMAGE_NAME }}:latest