# This workflow pre-builds the dev container docker image used in Github Codespaces or if you run the devcontainer locally
# This will pre-install all the container features.
# The image is PRIVATE to the orginization; regardless, no sensitive data is exposed to the package stored in ghcr.io.
name: Prebuild Dev Container

on:
  push:
    branches: [fix/multi-platform-build]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker images require lowercase names, but GitHub repository may contain uppercase characters
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Docker image used for local development (Dev Container) and CI testing
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/${{ env.REPO }}
          imageTag: ${{ matrix.os }}
          push: always

  combine:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push manifest
        run: |
          docker manifest create ghcr.io/jazz23/bounty-thing:latest --amend ghcr.io/jazz23/bounty-thing:ubuntu-24.04-arm --amend ghcr.io/jazz23/bounty-thing:ubuntu-latest
          docker manifest push ghcr.io/jazz23/bounty-thing:latest