# This workflow pre-builds the dev container docker image used in Github Codespaces or if you run the devcontainer locally
# This will pre-install all the container features.
# The image is PRIVATE to the orginization; regardless, no sensitive data is exposed to the package stored in ghcr.io.
name: Prebuild Dev Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github
          imageName: ghcr.io/${{ env.REPO }}
          cacheFrom: ghcr.io/${{ env.REPO }}
          push: always