name: Setup Dev Container

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load Dev Container Image
        uses: devcontainers/ci@v0.3
        with:
          push: never